name: Windows Installer

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "**/*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 插入這個步驟：注入 Token 權限
      - name: Setup Git Credentials
        run: |
          git config --global url."https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
        shell: bash

      - name: Configure (Release)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build (Release)
        run: cmake --build build --config Release

      - name: Install NSIS
        run: choco install nsis -y

      - name: Package (NSIS)
        working-directory: build
        run: cpack -G NSIS -C Release

      - name: Show NSIS log on failure
        if: failure()
        working-directory: build
        run: |
          if (Test-Path _CPack_Packages/win64/NSIS/NSISOutput.log) {
            Get-Content _CPack_Packages/win64/NSIS/NSISOutput.log
          } else {
            Write-Host 'NSISOutput.log not found'
          }
        shell: pwsh

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: MyuEngine-Windows-Installer
          path: build/*.exe